services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - NODE_ENV=production
    ports:
      - "30167:30167"
